### PR TITLE
Added a new project named - "Image Visualization"

### PR DESCRIPTION
**Pull request by RitwikGanguly**
A new project named 'Image visualization' is added. Also a readme.md file is added for the understanding purpose. The project is in jupyter notebook where there are comments attached.

### CODE REVIEW

**Comment by prashantkalokhe** [comment]
> A new project named 'Image visualization' is added. Also a readme.md file is added for the understanding purpose. The project is in jupyter notebook where there are comments attached.

Why do you delete other people Codes 10904 lines of code

**Comment by RitwikGanguly** [comment]
Actually I didn't delete, at the time of clone the other projects are not cloned, I wanted to reset the repo, but I can't and at the time of commit the rest of the files are deleted

**Comment by RitwikGanguly** [comment]
Do I re send the pull request in a better way

**Comment by prashantkalokhe** [comment]
Yes what you have done total messs in my repository

**Comment by RitwikGanguly** [comment]
What I did

**Comment by RitwikGanguly** [comment]
That was automatically deleted

**Pull request merged**
