### PR TITLE
missing number

### PR DESCRIPTION
**Pull request by Shalu461975**

### CODE REVIEW

**Comment by Shalu461975** [comment]
Please add hacktoberfest2022 level to get it accepted there because it is showing excluded on hacktober site

**Comment by prashantkalokhe** [comment]
How and where to add can you guide me

**Comment by Shalu461975** [comment]
> How and where to add can you guide me

I don't have any idea about it but your repo is showing excluded at hacktober site

**Comment by Shalu461975** [comment]
> > How and where to add can you guide me
> 
> I don't have any idea about it but your repo is showing excluded at hacktober site

May be you need to add hacktober fest 2022 lebal to the issue then only it would be considered

**Pull request merged**
